# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'PruebaiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PruebaiOS
  pod 'Alamofire', '~> 5.4'
  pod 'ViewAnimator'
  pod 'youtube-ios-player-helper'

  target 'PruebaiOSTests' do
    inherit! :search_paths
    pod 'Mocker'
    # Pods for testing
  end

  target 'PruebaiOSUITests' do
    # Pods for testing
  end

end
